---
title: "Citas"
author: "Luis Andrés Rojas García Exp. 279465"
date: "`r format(Sys.time(), '%B %d , %Y')`"
output: 
    html_document:
        toc: true
        toc_depth: 6
        collapsed: false
        smooth_scroll: true
bibliography: referencias.bib
csl: apa.csl
---

# Referencias para la tesis

# 2. Antecedentes

## 2.1. Características de los coronavirus y de SARS-CoV-2

### 2.1.1. Origen de la COVID-19

1. [@zhou2020pneumonia]

2. [@sharma2021covid]

3. [@sharma2021covid]

4. [@li2020evolutionary; @sharma2021covid]

### 2.1.2. Familia *coronaviridae*

5. [@GAURAV2019271; @BURRELL2017437]

6. [@BURRELL2017437; @murugan2021covid]

7. [@BURRELL2017437]

8. [@BURRELL2017437]

9. [@BURRELL2017437]

10. [@BURRELL2017437; @andersen2020proximal; @murugan2021covid]

### 2.1.3. Estructura los Coronavirus

11. [@GAURAV2019271; @BURRELL2017437]

### 2.1.4. Genoma de SARS-CoV-2

12. [@GAURAV2019271; @murugan2021covid]

13. [@GAURAV2019271; @murugan2021covid; @BURRELL2017437]

14. [@BURRELL2017437]

15. [@BURRELL2017437]

16. [@GAURAV2019271; @BURRELL2017437]

17. [@BURRELL2017437]

18. [@BURRELL2017437; @murugan2021covid]

19. [@dhama2022global; @tao2021biological]

### 2.1.5 Ciclo de replicación de SARS-CoV-2

20. [@salian2021covid; @pizzato2022sars; @harrison2020mechanisms]

21. [@salian2021covid]

22. [@salian2021covid; @harrison2020mechanisms; @pizzato2022sars; @BURRELL2017437]

23. [@salian2021covid; @pizzato2022sars]

24. [@BURRELL2017437]

25. [@harrison2020mechanisms; @pizzato2022sars; @BURRELL2017437]

26. [@harrison2020mechanisms]

27. [@harrison2020mechanisms; @pizzato2022sars]

28. [@BURRELL2017437; @harrison2020mechanisms]

29. [@BURRELL2017437]

30. [@harrison2020mechanisms; @pizzato2022sars]

### 2.1.6. Aparición del SARS-CoV-2

31. [@salian2021covid]

32. [@li2020evolutionary]

33. [@salian2021covid]

34. [@li2020evolutionary]

35. [@salian2021covid]

36. [@salian2021covid]

37. [@xiao2020isolation] en [@sharma2021covid]

38. [@xiao2020isolation] en [@sharma2021covid]

## 2.2. Pandemia por COVID-19

### 2.2.1 Transmisión del SARS-CoV-2

39. [@harrison2020mechanisms]

40. [@harrison2020mechanisms; @salian2021covid; @lotfi2020covid; @sharma2021covid]

41. [@morawska2020airborne]

42. [@morawska2020airborne]

43. [@salian2021covid; @sharma2021covid]

44. [@sharma2021covid; @lotfi2020covid; @harrison2020mechanisms]

45. [@sharma2021covid]

46. [@sharma2021covid]

47. [@sharma2021covid; @harrison2020mechanisms]

### 2.2.2. Manifestaciones clínicas

48. [@salian2021covid]

49. [@lotfi2020covid]

50. [@salian2021covid; @lotfi2020covid]

51. [@salian2021covid]

52. [@lotfi2020covid]

53. [@harrison2020mechanisms]

54. [@ssaludcovid]

#### 2.2.2.1. Respuestas inmunitarias ante el SARS-CoV-2

55. [@murugan2021covid]

56. [@murugan2021covid; @BURRELL2017437; @harrison2020mechanisms]

#### 2.2.2.2. Patogenesis del SARS-CoV-2

57. [@pizzato2022sars]

58. [@harrison2020mechanisms]

59. [@liao2020single; @harrison2020mechanisms]

60. [@harrison2020mechanisms]

61. [@puntmann2020outcomes; @liao2020single; @qin2020dysregulation; @chen2021sars; @nicholls2003lung; @channappanavar2017pathogenic; @varga2020endothelial; @hadjadj2020impaired; @harrison2020mechanisms]

#### 2.2.2.3. Etapas de la enfermedad

62. [@lauer2020incubation]

##### 2.2.2.3.1. Periodo de incubación

63. [@cdc2022CasesData]

64. [@murugan2021covid; @lauer2020incubation; @salian2021covid; @pizzato2022sars; @harrison2020mechanisms]

65. [@backer2020incubation; @lauer2020incubation]

66. [@linton2020incubation; @lauer2020incubation]

67. [@virlogeux2016comparison; @varia2003investigation; @lauer2020incubation]

68. [@acosta2022covid]

##### 2.2.2.3.2. Pacientes con sintomatología leve

69. [@lauer2020incubation]

70. [@oran2020prevalence]

71. [@he2021proportion]

##### 2.2.2.3.3. Infección clínica

72. [@salian2021covid]

73. [@cdc2022CasesData]

74. [@secsalud2021covid]

75. [@tsai2021clinical]


##### 2.2.2.3.4. Casos hospitalizados

76. [@cdc2022CasesData]

77. [@murugan2021covid]

78. [@fan2020clinical]

##### 2.2.2.3.5. Asistencia respiratoria

79. [@salian2021covid]

80. [@gibson2020covid; @acosta2022covid]

##### 2.2.2.3.6. Fallecimiento de los pacientes

81. [@cdc2022CasesData; @secsalud2021covid]

82. [@KLOK2020145; @murugan2021covid]

83. [@gibson2020covid]

84. [@wu2020risk; @gibson2020covid]

85. [@zhang2023risk]

86. [@wu2020estimating; @zhang2023risk]

#### 2.2.2.4. Post-Covid-19

87. [@oronsky2023review; @salamanna2021post; @pierce2022post; @chen2022global; @ncird2023afecciones]

### 2.2.3. Técnicas de diagnóstico y detección

88. [@kevadiya2021diagnostics]

89. [@murugan2021covid; @sharma2021covid]

90. [@guan2020clinical; @murugan2021covid]

91. [@guan2020clinical]

92. [@vandenberg2021considerations]

93. [@long2020diagnosis]

#### 2.2.3.1. Principales técnicas de detección de SARS-CoV-2

##### 2.2.3.1.1. RT-PCR

94. [@kevadiya2021diagnostics]

95. [@vandenberg2021considerations]

96. [@sharma2021covid]

97. [@chan2020familial]

98. [@corman2020detection]

99. [@sharma2021covid]

100. [@murugan2021covid]

101. [@vogels2020salivadirect]

102. [@murugan2021covid; @kevadiya2021diagnostics; @vandenberg2021considerations; @long2020diagnosis]

103. [@kevadiya2021diagnostics; @vandenberg2021considerations]

104. [@murugan2021covid]

##### 2.2.3.1.2. Radiología

105. [@murugan2021covid; @sharma2021covid]

106. [@murugan2021covid]

107. [@murugan2021covid; @sharma2021covid; @kevadiya2021diagnostics; @long2020diagnosis]

108. [@parekh2020review]

109. [@murugan2021covid; @kevadiya2021diagnostics]

110. [@wang2020temporal]

111. [@bernheim2020chest]

112. [@long2020diagnosis]

113. [@fang2020sensitivity]

114. [@sharma2021covid]

115. [@murugan2021covid]

116. [@loey2020within; @ozturk2020automated; @rahimzadeh2020modified; @huang2021artificial]

##### 2.2.3.1.3. Ensayos inmunológicos

117. [@murugan2021covid]

118. [@sharma2021covid]

119. [@kevadiya2021diagnostics]

120. [@safiabadi2021tools]

121. [@ejazi2021antibody]

122. [@murugan2021covid; @kevadiya2021diagnostics]

123. [@lv2020cross; @long2020antibody; @murugan2021covid]

124. [@kevadiya2021diagnostics]

125. [@kevadiya2021diagnostics]

126. [@safiabadi2021tools]

127. [@safiabadi2021tools]

128. [@safiabadi2021tools]

129. [@lab2022chopoa]

130. [@lab2022chopob]

131. [@amunet2022elisa]

##### 2.2.3.1.4. Kits de pruebas rápidas

132. [@sharma2021covid]

133. [@kevadiya2021diagnostics]

134. [@cdc2023rat]

135. [@yamayoshi2020comparison]

136. [@sharma2021covid; @cdc2023rat]

#### 2.2.3.2 Consideraciones de la OMS

137. [@10665-330861]

138. [@murugan2021covid; @kevadiya2021diagnostics; @liu2020positive]

139. [@surveillance2020owho]

140. [@10665-330861]

141. [@10665-330861]

142. [@10665-330861]

143. [@10665-330861]

144. [@10665-330861]

145. [@10665-330861]

146. [@10665-330861]

147. [@WHOpolicybrief2022]

#### 2.2.3.3 Técnicas aprobadas e implementadas en México

148. [@palomino2022identificacion]

149. [@cofepris2022pruebas]

150. [@cofepris2020pruebas]

151. [@indrelaboratorios]

### 2.2.4. Principales tratamientos y terapias implementados

152. [@murugan2021covid]

153. [@heymann2020covid; @sharma2021covid]

154. [@salian2021covid]

155. [@lotfi2020covid]

156. [@sharma2021covid]

### 2.2.5. Epidemiología de COVID-19

#### 2.2.5.1. Medidas de prevención epidemiológica para la detención de la pandemia

157. [@cdc2023proteccion]

158. [@secsaludprevencion]

159. [@whocoronavirus]

160. [@krittanawong2022covid]

##### 2.2.5.1.1. Vacunación

161. [@da2022two]

162. [@who2023vaccines]

#### 2.2.5.2. Factores de riesgo y protección

163. [@zhang2023risk]

164. [@pijls2021demographic; @zhang2023risk]

165. [@ayoub2020characterizing; @zhang2023risk]

166. [@wu2020estimating; @zhang2023risk]

167. [@liu2020positive; @zhang2023risk]

168. [@li2021epidemiology; @zhang2023risk]

169. [@guan2020comorbidity; @zhang2023risk]

170. [@bae2021impact; @zhang2023risk]

171. [@gao2021risk; @zhang2023risk]

172. [@hosseini2019type; @zhang2023risk]

173. [@hodgson2021defines; @zhang2023risk]

174. [@zhang2021safety; @wu2021safety; @zhang2023risk]

175. [@pawlowski2021fda; @zhang2023risk; @thompson2021interim]

#### 2.2.5.3. Epidemiología en México durante el incio de la pandemia

176. [@suarez2020epidemiologia]

### 2.2.6. Efectos de la pandemia en la población

#### 2.2.6.1. Diferencias en la edad

177. [@zhang2023risk]

178. [@kauhanen2023systematic]

179. [@inegi2022estadisticas]

#### 2.2.6.2. Cambios sociales por la pandemia

180. [@harper2021impact]

181. [@marois2020assessing; @harper2021impact]

183. [@paho2021disasters]

#### 2.2.6.3. Enfermedades re-emergentes

184. [@shapo2023could]

185. [@frutos2021covid]

## 2.3. Modelos matemáticos

### 2.3.1. Matemáticas en biología

186. [@alvarez2023matematica]

#### 2.3.1.1. Uso de modelos matemáticos

### 2.3.2. Modelos matemáticss epidemiológicos

187. [@grassly2008mathematical]

188. [@adiga2020mathematical]

189. [@al2023mathematical]

#### 2.3.2.1. Modelo SIR

189. [@ram2021modified]

#### 2.3.2.2. Modelos de COVID-19

190. [@kucharski2020early]

191. [@sun2020transmission]

192. [@ndairou2020mathematical]

193. [@samui2020mathematical]

194. [@cdmxmodelo]

195. [@zeb2020mathematical]

### 2.3.3. Modelos heterogéneos

196. [@wang2023mathematical]

197. [@berestycki2023epidemic]

#### 2.3.1.1. Modelos heterogéneos para COVID-19

198. [@ram2021modified; @ko2021risk; @duan2022heterogeneous; @blyuss2021effects; @lovell2022estimating; @lee2020children; @liu2020clinical; @chikina2020modeling; @zhang2023risk; @pezzullo2023age]

199. [@zhang2023risk; @secsalud2021covid]

200. [@ram2021modified; @ko2021risk; @duan2022heterogeneous; @blyuss2021effects; @lovell2022estimating; @lee2020children; @liu2020clinical; @chikina2020modeling; @pezzullo2023age]

# 3. Justificación del proyecto

201. [@pezzullo2023age]

202. [@santana2021covid]

203. [@kretzschmar2022challenges]

204. [@gozzi2021importance]

# M

- https://academic.oup.com/cid/article/74/9/1678/6359063 : Parámetros
- https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-021-05950-x
- https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/es/covidwho-606040
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7258488/

# D

- https://pubmed.ncbi.nlm.nih.gov/32685469/ : Modelo
- https://www.fisica.unam.mx/personales/mir/corona19/index.html
- https://edoc.rki.de/handle/176904/6547 : Deutschland
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7585674/
- https://pubmed.ncbi.nlm.nih.gov/33024342/ : Periodo de incubación
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7444295/ : Diferencias en la mortalidad de edad y sexo en Europa
- https://pubmed.ncbi.nlm.nih.gov/32470120/ : Diferencias de edad en riesgo COVID-19 y la salud mental
- https://pubmed.ncbi.nlm.nih.gov/33566457/#:~:text=As%20the%20immune%20system%20undergoes,of%20severity%20of%20COVID%2D19. : Diferencias en la edad
- https://pubmed.ncbi.nlm.nih.gov/33713603/ : Bajo riesgo de mortalidad en niños
- https://e-epih.org/journal/view.php?doi=10.4178/epih.e2021059 : Modelo heterogéneo COVID-19 Corea
- https://www.sciencedirect.com/science/article/pii/S0022519322002508 : Modelo heterogéneo COVID-19
- https://www.sciencedirect.com/science/article/pii/S0022519321004033?via%3Dihub : Modelo heterogéneo COVID-19




<br>

## 3. Fuentes de consulta

<br>







